[pm/cts] fix flaky testListPackageDefaultAllUsers
Example flakiness (after adding some logs at line 467):

java.lang.AssertionError: Current UIDs: package:com.example.helloworld
uid:10391,2610391, previous UIDs: package:com.example.helloworld
uid:10391,2810391

Bedstead can be slow at deleting users used in previous tests, causing
flakiness in testListPackageDefaultAllUsers where the test assumes that
the list of the users don't change during the test. Modify the test so
that we don't make any assumption on the other users currently active on
the device.

Also add some small tests for the MATCH_ARCHIVE flag.

BUG: 309806322
Test: atest
android.content.pm.cts.PackageManagerShellCommandMultiUserTest

Change-Id: Iabcb974f2894db65dfde1acc6eebd08f116cc060