BackupPreparer: Fix NoSuchMethodError for CtsBackupTestCases in MTS
CtsBackupTestCases fails with a NoSuchMethodError when run via the MTS.
This happens because the version of BackupUtils used in that context does not have the newer getCurrentUserId() method.

This change resolves the issue by removing the dependency.

Bug: 424158052
Test: run mts -m CtsBackupTestCases
Flag: TEST_ONLY
Change-Id: I0f738fa4e7006d0fc4fdb07fc9dfb984d0e05f73