Fixed for CtsLocaleManagerTestCases.
During CtsLocaleManagerTestCases module test run, observed below
permission error
 1) android.localemanager.cts.LocaleManagerSystemLocaleTest
        java.lang.RuntimeException: Caught exception
            at android.localemanager.cts.LocaleManagerSystemLocaleTest
            .setUpClass(LocaleManagerSystemLocaleTest.java:62)
        Caused by: java.lang.SecurityException: Permission Denial:
            getCurrentUser() from pid=5423, uid=1010120 requires
            android.permission.INTERACT_ACROSS_USERS

2) android.localemanager.cts.LocaleManagerTests
       java.lang.RuntimeException: Caught exception
           at android.localemanager.cts.LocaleManagerTests
           .setUpClass(LocaleManagerTests.java:128)
       Caused by: java.lang.SecurityException: Permission Denial:
           getCurrentUser() from pid=5423, uid=1010120 requires
           android.permission.INTERACT_ACROSS_USERS

Added android.permission.INTERACT_ACROSS_USERS permission.

Bug:
Test: Run below test, it's passing.
atest CtsLocaleManagerTestCases.

Change-Id: Ic7f368b25b51bbf5632c52bd2b9524584ea551ce
Signed-off-by: Ankit Agrawal <ankit.agarwal@intel.com>