Fixed CtsAppSearchTestUtils dependency on compatibility-device-util-axt.
It must be on static_libs, as that module is used by other modules,
which could cause a NoClassDefFoundError at runtime.

Fixes: 441390723
Test: atest AppSearchCoreTests:android.app.appsearch.AppSearchSessionInternalTest#testQuery_genericDocumentWrapsParentTypeForPolymorphism
Flag: TEST_ONLY

Change-Id: I8ab1a1d30c7311395e5bdfb60f3c3c09ba799532