Always cleanup device in BackKeyShortcutsTest
If `BackKeyShortcutsTest` fails it ends up leaving the device under test
in a bad state that will cause subsequent CTS test failures. This CL
makes use of auto-close for UinputDevice to cleanup even on test
failure.

Example of a failure causing subsequent failures:
```
$ atest CtsInputTestCases

armeabi-v7a CtsInputTestCases
-----------------------------
android.input.cts (57 Tests)
[1/57] android.input.cts.AppKeyCombinationsTest#testSYSRQ: PASSED (1.412s)
[2/57] android.input.cts.AppKeyCombinationsTest#testCtrlSpace: PASSED (1.210s)
[3/57] android.input.cts.AppKeyCombinationsTest#testCtrlAltZ: PASSED (1.313s)
[4/57] android.input.cts.BackKeyShortcutsTest#testBackKeyMetaShortcuts: FAILED (7.131s)

STACKTRACE:
java.lang.AssertionError: Failed to receive key event number 1
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertNotNull(Assert.java:713)
	at android.input.cts.BackKeyShortcutsTest.assertReceivedEventsCorrectlyMapped(BackKeyShortcutsTest.kt:84)
	at android.input.cts.BackKeyShortcutsTest.testBackKeyMetaShortcuts(BackKeyShortcutsTest.kt:111)

[5/57] android.input.cts.DrawingTabletTest#testCoordinateMappingOrientation180: ASSUMPTION_FAILED (28ms)
[6/57] android.input.cts.DrawingTabletTest#testCoordinateMappingOrientation270: ASSUMPTION_FAILED (3ms)
[7/57] android.input.cts.DrawingTabletTest#testCoordinateMappingOrientation0: ASSUMPTION_FAILED (28ms)
[8/57] android.input.cts.DrawingTabletTest#testCoordinateMappingOrientation90: ASSUMPTION_FAILED (2ms)
[9/57] android.input.cts.GamepadWithAccessibilityTest#testDeviceId: FAILED (22.244s)

STACKTRACE:
java.lang.RuntimeException: Did not receive device removed notification in time
	at com.android.cts.input.VirtualInputDevice.close(VirtualInputDevice.java:187)
	at android.input.cts.GamepadWithAccessibilityTest.testDeviceId(GamepadWithAccessibilityTest.kt:122)
```

Bug: 287393717
Bug: 320618784
Test: atest CtsInputTestCases
(cherry picked from https://googleplex-android-review.googlesource.com/q/commit:66c518a34a0fd5b86e6ccd757eaf7e592afe6d10)

Merged-In: Ica905293060d8657b06f55a4f27d39de91c0b630
Change-Id: Iec186179b9bb37efc767dcb7635f46c0dd85f447