Use proper @BeforeClass import and use anyInt()
Tests were recently updated and still have errors. Using any() causes
NPEs, which are solved by using anyInt(). Using the proper import fixes
the other blanket error.

Lastly, we need to allow our test to use platform api, so the sysprop
libraries will link at runtime. Otherwise, the linker throws
NoSuchMethodErrors when we try to call APIs that definitely exist

Flag: EXEMPT TEST_ONLY
Bug: 454493471
Test: atest android.car.cts.CarBluetoothTest
Change-Id: I4e10d5c4bdb26c32e66936acbe7758f83ca865c9