[C++23] gpuprofiling: Add missing chrono header
Add chrono header to fix C++23 build errors because C++23 removed
certain transitive includes

Errors:
cts/hostsidetests/graphics/gpuprofiling/app/jni/vulkan_renderer.cpp:271:35:
error: no member named 'chrono' in namespace 'std'
  271 |     auto gpuFrameStartTime =
std::chrono::high_resolution_clock::now();
cts/hostsidetests/graphics/gpuprofiling/app/jni/vulkan_renderer.cpp:274:32:
error: no member named 'chrono' in namespace 'std'
  274 |     lastFrameDurationMs = std::chrono::duration<double,
std::milli>(
cts/hostsidetests/graphics/gpuprofiling/app/jni/vulkan_renderer.cpp:275:40:
error: no member named 'chrono' in namespace 'std'
  275 |
std::chrono::high_resolution_clock::now() - gpuFrameStartTime)

Generated by Gemini.

Flag: EXEMPT PURE_REFACTOR
Bug: 429048222
Test: m libctsgraphicsgpuprofiling_jni
Change-Id: I2ff2347fc001766a1c041e0b7c1d76e9c49febdd