CtsDevicePolicyManagerTestCases operate:Test whether the contact function is normal.
In the current version of Honor mobile phone, a hotline number is preset in the contact.
This contact is preset in both the main user and the sub-user. An error is reported during the CTS test.
This use case writes 2 contact information in the sub-user, and then checks whether there are 2 contacts
in the contact, and the result is 3 contacts. Because the hotline number is pre-set in the sub-user's contacts.
When testing the CTS use case, the sub-user's contact data is not cleared in advance,
so there are 3 data and the test fails.

failure message：
I/BaseHostJUnit4Test: Test com.android.cts.managedprofile.ContactsTest#testManagedProfileContactList_canListManagedContacts: FAILURE
W/BaseHostJUnit4Test: junit.framework.AssertionFailedError: expected:<2> but was:<3>
at junit.framework.Assert.fail(Assert.java:50)
at junit.framework.Assert.failNotEquals(Assert.java:287)
at junit.framework.Assert.assertEquals(Assert.java:67)
at junit.framework.Assert.assertEquals(Assert.java:199)
at junit.framework.Assert.assertEquals(Assert.java:205)
at com.android.cts.managedprofile.ContactsTest.testManagedProfileContactList_canListManagedContacts(ContactsTest.java:340)

Bug:349932246

Change-Id: Iccd68bc4c97bbca1c21bb6a19eaecad41df73f64
Test:run cts -m CtsDevicePolicyManagerTestCases -t com.android.cts.devicepolicy.ManagedProfileContactsTest#testManagedContactsUris