Use annotation for flag checking
It seems like implementation of flag checking methods that were used
previously depends on Android framework classes that aren't available
on the host side, leading to NoSuchMethodError.

Bug: 434278289
Flag: TEST_ONLY
Test: atest CtsDevicePolicyManagerTestCases:com.android.cts.devicepolicy.ManagedProfileCrossProfileTest
Change-Id: I0750cf1e403f645332b9fe203318f40352b84e5d